version = 0.1

[default]
[default.global.parameters]
stack_name = "websocket-api-dev"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
region = "ap-northeast-1"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "websocket-api"
parameter_overrides = [
    "Environment=dev",
    "DatabaseUrl=REPLACE_WITH_DATABASE_URL"
]

